sudo: false

language: c

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-8.4.3
      - cabal-install-2.2

before_install:
  - export PATH=$HOME/.tinc/bin:/opt/ghc/8.4.3/bin:/opt/cabal/2.2/bin:$PATH
  - curl -sSL https://github.com/sol/tinc/raw/master/get-tinc.sh | bash
  - tinc --version
  - ghc --version
  - cabal --version
  - travis_retry cabal update
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config

install:
  - tinc

script:
  - cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test --show-details=direct

before_deploy:
  - cp dist/build/tinc/tinc .
  - gzip tinc
  - mv tinc.gz tinc-${TRAVIS_OS_NAME}.gz

deploy:
  provider: releases
  api_key:
    secure: ccgjywa/XIYrwiTnrOpiBuTFrBENAvZ4jOkZ7aNekTVpOo7ahq++G5Ke2n/a725FEO2Xldx1rUXVAiNnbEEHBwzd4bxig/mJUahEKJLkZWduEmzNrv/kcKtuOYV6OJrheF6hv6Jt8ACls6ezUuOrsyLz/4A3eS2Ca8JcLE2RHLcVm4OA5G9It1h8o6kM2okZNjkwggwK1HHMyRf7yfkikG2w/+3sF+6eVDJWVGEVmyvGPfeY323jpiFLrBdl9Q5/wIOrav+wn3NOIXJP4/iYOSHnxWt8AwlV0Hl97ClN1ifM02YwnEEwF0nFNOf0mEOa169sZX4cN8IouNUNEtprv7QO+ZTYui12R654qp6CFauWUQTJueAgrcXVshIQcZ9Xx03bjy/qnGIQIlQzzMbrBxhtSjVwmTYX/4sYHFyz10EzlFouylFM6gi5NEMHadIkEmuWo78nSjkddAPaFTFHzxUuvtm5Z+MAW+MarHNgES3qX/kReOx0XD0WXz0DBKSUyXoNbIvEZKAVqH6SJap+eodzUW8G1JjJqjQ0tO3IhDm0IHWc9riMyYxM11gApPezVlKAvnk/T+/trHot5+YVvdQ0MmcqJWpFfHbBStAXGA7X22nzX4SrwfvaoUJF6rtNRS5D9W/Ior996GNDD9OwmWBgmc2dsOn7S99lKOFhejI=
  file_glob: true
  file: tinc-*.gz
  skip_cleanup: true
  on:
    repo: sol/tinc
    tags: true

cache:
  directories:
    - $HOME/.tinc/cache
