name: tinc
version: 0.1.0
category: Development
license: MIT
copyright:
  - (c) 2015 Sönke Hahn
  - (c) 2015-2017 Simon Hengel
author: Simon Hengel <sol@typeful.net>
maintainer: Simon Hengel <sol@typeful.net>

github: sol/tinc

extra-source-files:
  - test/resources/*

ghc-options: -Wall -fwarn-redundant-constraints

dependencies:
  - base >= 4.11
  - graph-wrapper >= 0.2.5
  - language-dot
  - containers
  - directory
  - filepath
  - filelock
  - process >= 1.2
  - parsec
  - temporary
  - exceptions
  - transformers
  - hpack >= 0.30.0
  - aeson >= 0.11.0
  - bytestring
  - yaml
  - Cabal >= 2.0.0.2
  - gitrev
  - unix-compat
  - call-stack
  - time
  - store

source-dirs: src

executables:
  tinc:
    main: tinc.hs
    source-dirs: driver

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - mockery >= 0.3.3
      - HUnit >= 1.4
      - safe
      - unix
      - QuickCheck
    cpp-options: -DTEST
