name: tinc
version: 0.1.0
category: Development
license: MIT
copyright:
  - (c) 2015 Sönke Hahn
  - (c) 2015-2016 Simon Hengel
author: Simon Hengel <sol@typeful.net>
maintainer: Simon Hengel <sol@typeful.net>

github: sol/tinc

extra-source-files:
  - test/resources/*

ghc-options: -Wall

dependencies:
  - base >= 4.8
  - graph-wrapper >= 0.2.5
  - language-dot
  - containers
  - directory
  - filepath
  - filelock
  - process >= 1.2
  - parsec
  - temporary
  - exceptions
  - transformers
  - hpack >= 0.12.0
  - aeson >= 0.11.0
  - bytestring
  - yaml
  - Cabal == 1.22.*
  - gitrev
  - unix-compat
  - with-location
  - time
  - text
  - template

source-dirs: src

executables:
  tinc:
    main: tinc.hs
    source-dirs: driver

tests:
  spec:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - hspec
      - mockery >= 0.3.3
      - HUnit >= 1.3
      - safe
      - unix
    cpp-options: -DTEST
