name: stack-sandbox
version: "0.1"
category: Development
license: "BSD3"
author: "Sönke Hahn"
copyright: "Sönke Hahn"
maintainer: "soenke.hahn@zalora.com"
github: soenkehahn/link-sandbox

ghc-options: -Wall -fno-warn-name-shadowing

dependencies:
  - base == 4.*
  - base-compat
  - graph-wrapper
  - language-dot
  - containers
  - directory
  - filepath
  - process >= 1.2
  - getopt-generics
  - parsec

library:
  source-dirs:
    - src

executables:
  stack-sandbox:
    main: stack-sandbox.hs
    source-dirs:
      - src
      - driver

tests:
  spec:
    main: "Spec.hs"
    ghc-options: "-threaded -O0"
    source-dirs:
      - src
      - test

    dependencies:
      - hspec
      - hspec-expectations
      - mockery
      - silently
